// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bamslgczrnayvyqkykvu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJhbXNsZ2N6cm5heXZ5cWt5a3Z1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxNDg3OTUsImV4cCI6MjA2OTcyNDc5NX0.eAWPlvm8h9xz0UfYpPkbx3u4eufKkrXe-AFiIeBdnwk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});